name: Scope tests

on: [push]

jobs:
  tests:
    env:
      SCOPE_DSN: https://365d5b712fe047848d1a4e861dd38b41@app.scope.dev/
      SCOPE_CODE_PATH_ENABLED: true
      SCOPE_RUNNER_ENABLED: true
      SCOPE_INSTRUMENTATION_HTTP_PAYLOADS: true
      SCOPE_INSTRUMENTATION_DB_STATEMENT_VALUES: true
      CI: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn
      - name: Bootstrap
        run: yarn bootstrap
      - name: Run unit tests
        run: yarn test:unit
      - name: Build demo
        run: yarn build:demo
      - name: Run e2e tests
        run: yarn test:e2e:run
